### ISSUE TITLE
Regression of #207 (colored output and link detection)

### ISSUE THREAD

**Issue by dgazzoni** [matepek/vscode-catch2-test-adapter#268]
**Checklist**

- [X] The issue is about this extension and NOT about a fork.
- [X] Check the [known issues](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md#known-issues) list.
- [X] The latest version of the extension was used.
- [X] It is not related to remote-vscode or I checked the following [issue](https://github.com/matepek/vscode-catch2-test-adapter/issues/201)

**Describe the bug**

A regression of #207. File links aren't working for me at all. They do work with the provided 3.2.6-dev2 version in that issue (see [this comment](https://github.com/matepek/vscode-catch2-test-adapter/issues/207#issuecomment-648625189) in #207), or if I uninstall the extension.

Since #207 was closed, and my comments about a month ago there weren't acknowledged, I'm opening a new issue.

**To Reproduce**

1. Install CMake Tools and the latest version of C++ TestMate (3.6.26 as of this writing).
2. Open a project.
3. Insert a compilation error in one of the files.
4. Start a build.
5. In the output window, where the compiler indicates the file and line where the error occurred, try to Cmd-click on it. Notice that it doesn't work.
6. Uninstall C++ TestMate.
7. Reload VS Code.
8. Repeat steps 2-5, and notice that Cmd-click now works.

**Screenshots** (optional)

**Desktop**

- Extension Version: 3.6.26
- VS Code Version: 1.56.2
- Catch2 / Google Test / DOCTest Version: irrelevant
- OS Type and Version: macOS Catalina 10.15.7
- Using remote-ssh/docker/wsl?: no

**Regression bug?**

Yes.

- Last extension version in which the feature were working: 3.2.6-dev2 (as explained above and linked on #207)

**Log** (optional but recommended)

**Comment by matepek** [comment]
Note to myself: 
> However some other big changes are coming in months which will make this issue irrelevant.

**Comment by dgazzoni** [comment]
Sorry about that. As soon as I created this regression, I saw your comment in #207. I wouldn't have created it if I had seen the comment first.

**Comment by matepek** [comment]
No problem.

If you want you can create a PR. I'm happy to review it

**Comment by matepek** [comment]
Dear User(s),

Version 4+ has been release. Hoping it makes this issue resolved.
If you disagree then please comment `!open`.
